name: practice signle workflow variables

on: workflow_dispatch

env: 
  cloud: google-cloud
  
jobs:
  Greetings:
    runs-on: ubuntu-latest
    env:
      greeting_name: Hello!
    steps:
      - name: Hello my name is fahad
        run: echo $greeting_name $First_name is using $cloud
        env:
          First_name: Fahad
      
