name: practice single workflow variables

on: workflow_dispatch

env: 
  cloud: google-cloud
  greeting_name: Hello!
  First_name: Fahad

jobs:
  Greetings:
    runs-on: ubuntu-latest      
    steps:
      - name: Say_Greetings
        run: echo $greeting_name $First_name is using $cloud
          
      
